### ISSUE TITLE
bind mounting /opt

### ISSUE THREAD

**Issue by mmxcscs** [NERSC/shifter#63]
Hello,

It is a minor issue, but Shifter bind mounts /opt to add SSH support.
However, it is possible that the original /opt is required on the image, in our case we have a set of specific software installed in it. Why not creating a specific path (/shifter) for Shifter support?

Thanks,
Maxime

**Comment by dmjacobsen** [comment]
Hi Maxime,

Shifter creates a new /opt in the image and then should bind mount everything from the image _plus_ the udiImage stuff into opt.  As it is designed the user should get everything in opt that they request.  I chose to put it in opt because shifter already had special handling for opt; this is because I anticipated that sites might want to import paths (siteFs mounts) into opt.

Can you describe the specifics of the issue you are having?  Because as far as I understand things right now, any thing in the user /opt should be in the container so long as it isn't named "udiImage" or conflict with a siteFs mount.

-Doug

**Comment by mmxcscs** [comment]
Hi Doug,

I guess that /opt is missing in our siteFS. Sorry for the noise. We will add it.

Thanks,
Maxime
